### ISSUE TITLE
Money Laundering

### ISSUE THREAD

**Issue by NeoBeum** [ALFAcoins/alfacoins-for-woocommerce#1]
No one has bothered to reply to my email..

So I'm going to plaster your social media until I get a valid response.

or, is the main purpose of your company to help criminals steal cryptocurrency?

**Comment by NeoBeum** [comment]
You have 48 hours before I start forwarding stuff to Interpol

**Comment by NeoBeum** [comment]
Actually, I probably will end up contacting Interpol despite what ALFAcoin replies with, as I feel that you have failed to comply with AML and verification with merchants using your platform.

**Comment by ALFAcoins** [comment]
@NeoBeum 

We've replied to your ticket within 2 hour frame.

Just in case you lost the link to the ticket, here it is - https://www.alfacoins.com/support/ticket/1598

Let's keep the conversation in the ticket.

Let me quote it as it seems you didn't get that reply inside your e-mail:

> Dear customer,
We're happy to assist if we receive an official request from police or interpol.
We're glad to provide all necessary details to any law enforcement officer.
Thank you.
--
Best regards,
ALFAcoins support team
